from database.db_config import conectar_banco
from main import main

def criar_tabelas():
    tabelas_sql = """
    CREATE TABLE OPERADOR (
        id_operador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100),
        experiencia NUMBER,
        tipo_colheita VARCHAR2(50)
    );

    CREATE TABLE MAQUINA (
        id_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        modelo VARCHAR2(100),
        fabricante VARCHAR2(100),
        ano NUMBER
    );

    CREATE TABLE COLHEITA (
        id_colheita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_operador NUMBER,
        id_maquina NUMBER,
        data_colheita DATE,
        area_colhida NUMBER,
        tipo_colheita VARCHAR2(50),
        quantidade_colhida NUMBER,
        perda_estimada NUMBER,
        CONSTRAINT fk_operador FOREIGN KEY (id_operador) REFERENCES OPERADOR(id_operador),
        CONSTRAINT fk_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina)
    );
    """
    try:
        conexao = conectar_banco()
        cursor = conexao.cursor()
        for comando in tabelas_sql.strip().split(";"):
            if comando.strip():
                try:
                    cursor.execute(comando)
                except Exception as e:
                    print(f"Tabela já existe ou erro ao criar: {e}")
        conexao.commit()
        conexao.close()
        print("Tabelas criadas com sucesso (se necessário)!")
    except Exception as e:
        print("Erro ao criar tabelas:")
        print(e)

if __name__ == "__main__":
    criar_tabelas()
    main()