CREATE TABLE OPERADOR (
    id_operador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    experiencia NUMBER,
    tipo_colheita VARCHAR2(50)
);

CREATE TABLE MAQUINA (
    id_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(100),
    fabricante VARCHAR2(100),
    ano NUMBER
);

CREATE TABLE COLHEITA (
    id_colheita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operador NUMBER,
    id_maquina NUMBER,
    data_colheita DATE,
    area_colhida NUMBER,
    tipo_colheita VARCHAR2(50),
    quantidade_colhida NUMBER,
    perda_estimada NUMBER,
    CONSTRAINT fk_operador FOREIGN KEY (id_operador) REFERENCES OPERADOR(id_operador) ON DELETE CASCADE,
    CONSTRAINT fk_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina) ON DELETE SET NULL
);
